-- Insert all TCN Nigeria branches
INSERT INTO campuses (name, address, service_times, country) VALUES
-- Nigeria Branches
('TCN Abuja', 'Ladi Kwali Hall, Abuja Continental Hotel (formerly SHERATON), Abuja', ARRAY['7:30am', '9:30am'], 'Nigeria'),
('TCN Abule-Egba', 'Heritage Mall, U-Turn B/Stop, Lagos/Abeokuta Express Way, Abule-Egba, Lagos', ARRAY['7:30am', '9:30am'], 'Nigeria'),
('TCN Ajah', 'Filmhouse Cinemas – Ikota Blackbell Mall, Lekki, Lagos', ARRAY['7:45am'], 'Nigeria'),
('TCN Badagry', 'Sycomore Hotels (Event Hall), No 1 Seje Road, Ajara-Topa, Badagry', ARRAY['9:00am'], 'Nigeria'),
('TCN Badore', 'Genesis Hall, Akins Bus stop, by Wema Bank, Addo Road', ARRAY['9:00am'], 'Nigeria'),
('TCN Egbeda', 'Grand Ovation Centre, Moshalashi Bus Stop, Beside Mobil Filling Station, Idimu Road, Egbeda, Lagos', ARRAY['9:00am'], 'Nigeria'),
('TCN Festac', 'The Covenant Nation Festac, 1st Avenue, Beside i-Fitness Gym, Festac Town', ARRAY['7:15am', '9:00am'], 'Nigeria'),
('TCN Ibadan', 'Pentonrise Event Centre, Housing, Awolowo Road, Bodija, Ibadan', ARRAY['9:00am'], 'Nigeria'),
('TCN Ibeju-Lekki', '9, Oluwatoyin Dada Street, Winners Estate, Off Elemoro Palace Road, Ibeju-Lekki', ARRAY['9:00am'], 'Nigeria'),
('TCN Igando', 'Lagos Theatre Igando, No. 88, College Street, NYSC Bus Stop, LASU/Isheri Road, Igando', ARRAY['7:15am', '9:00am'], 'Nigeria'),
('TCN Iganmu', 'The Covenant Place, Iganmu, Right Beside The National Art Theatre, Lagos', ARRAY['6:30am', '8:15am', '10:30am'], 'Nigeria'),
('TCN Ikeja', '32 Kudirat Abiola Way (by Polaris Bank), Oregun, Ikeja', ARRAY['7:30am', '9:30am'], 'Nigeria'),
('TCN Ikorodu', 'Dream Parks and Gardens, Off Radio Road by Hilltop Estate, Obafemi Awolowo Road, Ikorodu', ARRAY['7:15am', '9:00am'], 'Nigeria'),
('TCN Isolo', 'The Covenant Nation, 23, Adebisi Omotola Street by Asuani Police Station, Off Victoria Street, Isolo, Lagos', ARRAY['7:00am', '9:30am'], 'Nigeria'),
('TCN Karu', 'FrankVille Hotel, 10 Ngaram S.K Street, Fepa Quarters, After Customs Hospital, Karu Site, Abuja', ARRAY['8:30am'], 'Nigeria'),
('TCN Ketu-Ikosi', 'Centre for Management Development, CMD Avenue, Management Village Shangisha, Ketu, Lagos', ARRAY['9:00am'], 'Nigeria'),
('TCN Kubwa', 'Cenon Pavilion, Adjacent to Arlington Hotel, PW 181 Bakori Road, Kubwa, Abuja', ARRAY['8:30am'], 'Nigeria'),
('TCN Lekki', 'The Covenant Temple, Lekki, Chisco Bus-Stop, Behind Enyo Fuel Station, Lekki', ARRAY['7:45am', '10:00am'], 'Nigeria'),
('TCN Maryland', '370 Ikorodu Road, Maryland, Lagos', ARRAY['7:00am', '9:00am'], 'Nigeria'),
('TCN Mowe-Arepo', '58/60 Journalist Road, Arepo (Beside DUX FM)', ARRAY['8:00am'], 'Nigeria'),
('TCN Mushin/Oshodi', 'Digital Bridge Institute, 1, NITEL Road, Old NITEL Training School, Cappa Bus Stop', ARRAY['8:00am'], 'Nigeria'),
('TCN Ogba', 'Philjul Events Gallery, Off Ogba Ogunji Road, Behind AP Filling Station, Ogba, Lagos', ARRAY['8:30am'], 'Nigeria'),
('TCN Orchid Road', '100 Mega-1 Event Way, Orchid Road, Lekki, Lagos', ARRAY['8:00am'], 'Nigeria'),
('TCN Satellite Town', 'Mater DEI School, 102-106 Marwa Road, Satellite Town, Lagos', ARRAY['8:00am'], 'Nigeria'),
('TCN Sangotedo', 'KM22 Lekki-Epe Expressway, Opposite Lagos Business School', ARRAY['7:45am'], 'Nigeria'),
('TCN Port Harcourt', 'Hotel Presidential, 1 Birabi Street, GRA, Port Harcourt', ARRAY['8:30am'], 'Nigeria'),
('TCN Uyo', 'VINPY Hotels and Event Centre, 10 Udo Udoma Avenue, Uyo', ARRAY['7:30am', '9:30am'], 'Nigeria'),
('TCN Victoria Island', 'Lagoon Restaurant, Ozumba Mbadiwe, Victoria Island, Lagos', ARRAY['9:00am'], 'Nigeria'),
('TCN Yaba', '400, Herbert Macaulay Road, Yaba, Lagos', ARRAY['6:30am', '8:30am'], 'Nigeria'),
('Covenant Connect', 'The Covenant Nation, 400 Herbert Macaulay Way, Yaba, Lagos', ARRAY['11:30am'], 'Nigeria'),

-- Global Branches
('TCN Birmingham', 'Odeon Cinemas, 139 New Street, Birmingham B2 4NU', ARRAY['10:00am GMT'], 'United Kingdom'),
('TCN Calgary', 'Auditorium 11, Cineplex Cinema Chinook Mall, 6455 Macleod Trail SW, Calgary, AB T2H 0K9', ARRAY['9:30am MST'], 'Canada'),
('TCN Mississauga', '1465 Leda Avenue, Mississauga, ON, Canada', ARRAY['10:00am ET'], 'Canada'),
('TCN Central London', 'Richard Cobden Primary School, Camden Street, NW1 0LL, London', ARRAY['10:00am GMT'], 'United Kingdom'),
('TCN Dublin', 'Clayton Hotel, Leopardstown, Central Park, Sandyford 18', ARRAY['10:00am GMT'], 'Ireland'),
('TCN New York City', '1021 Rutland Road, Brooklyn, NY 11212', ARRAY['10:00am ET'], 'United States'),
('TCN Manchester', 'Dean Trust Ardwick, 345 Stockport Road, Manchester, M13 0LF', ARRAY['10:00am GMT'], 'United Kingdom'),
('TCN Lewisham', 'Main Hall, Prendergast Ladywell School, Catford, Lewisham, SE4 1SA', ARRAY['10:00am GMT'], 'United Kingdom');